/*
 * Copyright (c) 2016-2019, Leftshift One
 * __________________
 * [2019] Leftshift One
 * All Rights Reserved.
 * NOTICE:  All information contained herein is, and remains
 * the property of Leftshift One and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Leftshift One
 * and its suppliers and may be covered by Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Leftshift One.
 */

// automatically generated by the FlatBuffers compiler, do not modify

package keios.protocol.lucene.flatbuffers;

import java.nio.*;
import java.lang.*;

import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class LuceneReadResponse extends Table {
  public static LuceneReadResponse getRootAsLuceneReadResponse(ByteBuffer _bb) { return getRootAsLuceneReadResponse(_bb, new LuceneReadResponse()); }
  public static LuceneReadResponse getRootAsLuceneReadResponse(ByteBuffer _bb, LuceneReadResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public LuceneReadResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SearchResult results(int j) { return results(new SearchResult(), j); }
  public SearchResult results(SearchResult obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int resultsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createLuceneReadResponse(FlatBufferBuilder builder,
      int resultsOffset) {
    builder.startObject(1);
    LuceneReadResponse.addResults(builder, resultsOffset);
    return LuceneReadResponse.endLuceneReadResponse(builder);
  }

  public static void startLuceneReadResponse(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addResults(FlatBufferBuilder builder, int resultsOffset) { builder.addOffset(0, resultsOffset, 0); }
  public static int createResultsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startResultsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endLuceneReadResponse(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

