/*
 * Copyright (c) 2016-2019, Leftshift One
 * __________________
 * [2019] Leftshift One
 * All Rights Reserved.
 * NOTICE:  All information contained herein is, and remains
 * the property of Leftshift One and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Leftshift One
 * and its suppliers and may be covered by Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Leftshift One.
 */

// automatically generated by the FlatBuffers compiler, do not modify

package keios.protocol.gensim.flatbuffers;

public final class GensimMessageType {
  private GensimMessageType() { }
  public static final byte NONE = 0;
  public static final byte GensimFastTextEmbeddingRequest = 1;
  public static final byte GensimFastTextEmbeddingResponse = 2;
  public static final byte GensimFastTextMostSimilarRequest = 3;
  public static final byte GensimFastTextMostSimilarResponse = 4;
  public static final byte GensimFastTextSimilarityRequest = 5;
  public static final byte GensimFastTextSimilarityResponse = 6;

  public static final String[] names = { "NONE", "GensimFastTextEmbeddingRequest", "GensimFastTextEmbeddingResponse", "GensimFastTextMostSimilarRequest", "GensimFastTextMostSimilarResponse", "GensimFastTextSimilarityRequest", "GensimFastTextSimilarityResponse", };

  public static String name(int e) { return names[e]; }
}

