# automatically generated by the FlatBuffers compiler, do not modify

# namespace: spacy

class SpacyMessageType(object):
    NONE = 0
    SpacyRequest = 1
    SpacyBatchRequest = 2
    SpacyResponse = 3
    SpacyBatchResponse = 4

