/*
 * Copyright (c) 2016-2019, Leftshift One
 * __________________
 * [2019] Leftshift One
 * All Rights Reserved.
 * NOTICE:  All information contained herein is, and remains
 * the property of Leftshift One and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Leftshift One
 * and its suppliers and may be covered by Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Leftshift One.
 */

// automatically generated by the FlatBuffers compiler, do not modify

package keios.protocol.classification.class2.flatbuffers;

import java.nio.*;
import java.lang.*;

import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ClassificationClass2Request extends Table {
  public static ClassificationClass2Request getRootAsClassificationClass2Request(ByteBuffer _bb) { return getRootAsClassificationClass2Request(_bb, new ClassificationClass2Request()); }
  public static ClassificationClass2Request getRootAsClassificationClass2Request(ByteBuffer _bb, ClassificationClass2Request obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public ClassificationClass2Request __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Vector vectors(int j) { return vectors(new Vector(), j); }
  public Vector vectors(Vector obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int vectorsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createClassificationClass2Request(FlatBufferBuilder builder,
      int vectorsOffset) {
    builder.startObject(1);
    ClassificationClass2Request.addVectors(builder, vectorsOffset);
    return ClassificationClass2Request.endClassificationClass2Request(builder);
  }

  public static void startClassificationClass2Request(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addVectors(FlatBufferBuilder builder, int vectorsOffset) { builder.addOffset(0, vectorsOffset, 0); }
  public static int createVectorsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startVectorsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endClassificationClass2Request(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishClassificationClass2RequestBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedClassificationClass2RequestBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }
}

