// automatically generated by the FlatBuffers compiler, do not modify

package keios.protocol.nlpaug.text.augmenter;

public final class TextAugmenter {
  private TextAugmenter() { }
  public static final byte NONE = 0;
  public static final byte RandomWordAugmenter = 1;
  public static final byte FastTextAugmenter = 2;
  public static final byte TfIdfAugmenter = 3;
  public static final byte BertAugmenter = 4;
  public static final byte SyntaxTreeAugmenter = 5;

  public static final String[] names = { "NONE", "RandomWordAugmenter", "FastTextAugmenter", "TfIdfAugmenter", "BertAugmenter", "SyntaxTreeAugmenter", };

  public static String name(int e) { return names[e]; }
}

