// automatically generated by the FlatBuffers compiler, do not modify

package keios.protocol.nlpaug.text.augmenter;

import java.nio.*;
import java.lang.*;

import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class TextAugmentation extends Table {
  public static TextAugmentation getRootAsTextAugmentation(ByteBuffer _bb) { return getRootAsTextAugmentation(_bb, new TextAugmentation()); }
  public static TextAugmentation getRootAsTextAugmentation(ByteBuffer _bb, TextAugmentation obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public TextAugmentation __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte augmentersType(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) : 0; }
  public int augmentersTypeLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer augmentersTypeAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer augmentersTypeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public Table augmenters(Table obj, int j) { int o = __offset(6); return o != 0 ? __union(obj, __vector(o) + j * 4) : null; }
  public int augmentersLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }

  public static int createTextAugmentation(FlatBufferBuilder builder,
      int augmenters_typeOffset,
      int augmentersOffset) {
    builder.startObject(2);
    TextAugmentation.addAugmenters(builder, augmentersOffset);
    TextAugmentation.addAugmentersType(builder, augmenters_typeOffset);
    return TextAugmentation.endTextAugmentation(builder);
  }

  public static void startTextAugmentation(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addAugmentersType(FlatBufferBuilder builder, int augmentersTypeOffset) { builder.addOffset(0, augmentersTypeOffset, 0); }
  public static int createAugmentersTypeVector(FlatBufferBuilder builder, byte[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addByte(data[i]); return builder.endVector(); }
  public static void startAugmentersTypeVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addAugmenters(FlatBufferBuilder builder, int augmentersOffset) { builder.addOffset(1, augmentersOffset, 0); }
  public static int createAugmentersVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startAugmentersVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endTextAugmentation(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

