# automatically generated by the FlatBuffers compiler, do not modify

# namespace: pocketsphinx

import flatbuffers

class PocketsphinxResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPocketsphinxResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PocketsphinxResponse()
        x.Init(buf, n + offset)
        return x

    # PocketsphinxResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PocketsphinxResponse
    def Guesses(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Guess import Guess
            obj = Guess()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PocketsphinxResponse
    def GuessesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def PocketsphinxResponseStart(builder): builder.StartObject(1)
def PocketsphinxResponseAddGuesses(builder, guesses): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(guesses), 0)
def PocketsphinxResponseStartGuessesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def PocketsphinxResponseEnd(builder): return builder.EndObject()
