# automatically generated by the FlatBuffers compiler, do not modify

# namespace: pocketsphinx

class PocketSphinxMessageType(object):
    NONE = 0
    PocketSphinxRequest = 1
    PocketSphinxResponse = 2

