webhook-created: &webhook-created
  name: Webhook created
  command: |
    curl $BUILD_STATUS_URL\?flow\=circleci-created -d '{"repository":"'"$CIRCLE_PROJECT_REPONAME"'","branch":"'"$CIRCLE_BRANCH"'","build_number":"'"$CIRCLE_BUILD_NUM"'","build_url":"'"$CIRCLE_BUILD_URL"'"}' -H "Content-Type: application/json" -X POST -i || true
webhook-failed: &webhook-failed
  name: Webhook completed
  when: on_fail
  command: |
    curl $BUILD_STATUS_URL\?flow\=circleci-completed\&status\=FAILED -d '{"repository":"'"$CIRCLE_PROJECT_REPONAME"'","branch":"'"$CIRCLE_BRANCH"'","build_number":"'"$CIRCLE_BUILD_NUM"'","build_url":"'"$CIRCLE_BUILD_URL"'"}' -H "Content-Type: application/json" -X POST -i || true

version: 2.1
jobs:
  webhook-completed:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - run:
          name: Webhook completed
          command: |
            curl $BUILD_STATUS_URL\?flow\=circleci-completed -d '{"repository":"'"$CIRCLE_PROJECT_REPONAME"'","branch":"'"$CIRCLE_BRANCH"'","build_number":"'"$CIRCLE_PREVIOUS_BUILD_NUM"'","build_url":"'"$CIRCLE_BUILD_URL"'"}' -H "Content-Type: application/json" -X POST -i || true
  build-java:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    environment:
      TZ: "/usr/share/zoneinfo/Europe/Vienna"
      GRADLE_OPTS: '-Xmx128m -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"'
      TEST_RESULTS_PATH: build/circleci/test-results
    steps:
      - run:
          <<: *webhook-created
      - checkout
      - run: chmod a+x gradlew
      - restore_cache:
          key: cache-gradle-{{ checksum "build.gradle" }}
      - run: ./gradlew dependencies
      - run: mkdir -p $TEST_RESULTS_PATH
      - run: ./gradlew test --stacktrace
      - run: find . -type f -regex ".*/build/test-results/test/.*xml" -exec cp {} $TEST_RESULTS_PATH \;
      - run: ./gradlew assemble --stacktrace
      - save_cache:
          paths:
            - ~/.gradle
          key: cache-gradle-{{ checksum "build.gradle" }}
      - store_test_results:
          path: build/circleci/test-results
      - run:
          <<: *webhook-failed
  build-python:
    docker:
      - image: circleci/python:3.7.3
    environment:
      TZ: "/usr/share/zoneinfo/Europe/Vienna"
      TEST_RESULTS_PATH: build/circleci/test-results
    steps:
      - run:
          <<: *webhook-created
      - checkout
      - run: mkdir -p $TEST_RESULTS_PATH
      - run: pip install poetry==0.12.17
      - run: sudo apt-get install -qq build-essential swig libpulse-dev libasound2-dev
      - run: cd ~/project/python && poetry install
      - run: cd ~/project/python && poetry run install
      - run: cd ~/project/python && poetry run test-ci
      - run: cd ~/project/python && poetry run build
      - store_test_results:
          path: build/circleci/test-results
      - run:
          <<: *webhook-failed
  release-java:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    environment:
      TZ: "/usr/share/zoneinfo/Europe/Vienna"
      GRADLE_OPTS: '-Xmx128m -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"'
      TEST_RESULTS_PATH: build/circleci/test-results
    steps:
      - run:
          <<: *webhook-created
      - add_ssh_keys:
          fingerprints:
            - "e6:4b:54:bb:ce:9c:68:e3:86:fb:0c:82:e6:a9:37:41"
      - checkout
      - run: chmod a+x gradlew
      - run: ./gradlew dependencies
      - run: mkdir -p $TEST_RESULTS_PATH
      - run: echo 'export TARGET_MODULE=${CIRCLE_TAG#*-*-}' >> $BASH_ENV && source $BASH_ENV
      - run: echo 'export RELEASE_SCOPE=$(echo ${CIRCLE_TAG//release-/} | grep -P "^(major|minor|patch)" -o)' >> $BASH_ENV && source $BASH_ENV
      - run: "./gradlew :${TARGET_MODULE}:prepareVersions -Prelease.scope=${RELEASE_SCOPE} -s"
      - run: echo 'export RELEASE_VERSION=$(cat ./java/$TARGET_MODULE/build/release-version.txt)' >> $BASH_ENV && source $BASH_ENV
      - run: echo 'export DEV_VERSION=$(cat ./java/$TARGET_MODULE/build/dev-version.txt)' >> $BASH_ENV && source $BASH_ENV
      - run: git config --local user.email "ci@leftshift.one" && git config --local user.name "Continuous Integration"
      - run: git checkout master && git pull --tags
      - run: "./gradlew :${TARGET_MODULE}:release -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=${RELEASE_VERSION} -Prelease.newVersion=${DEV_VERSION} -s"
      - run:
          name: Cleanup release
          when: on_fail
          command: git push -d origin release-minor-$TARGET_MODULE
      - run:
          <<: *webhook-failed
  release-python:
    docker:
      - image: circleci/python:3.7.3
    environment:
      TZ: "/usr/share/zoneinfo/Europe/Vienna"
      TEST_RESULTS_PATH: build/circleci/test-results
    steps:
      - run:
          <<: *webhook-created
      - add_ssh_keys:
          fingerprints:
            - "e6:4b:54:bb:ce:9c:68:e3:86:fb:0c:82:e6:a9:37:41"
      - checkout
      - run: mkdir -p $TEST_RESULTS_PATH
      - run: pip install poetry==0.12.17
      - run: sudo apt-get install -qq build-essential swig libpulse-dev libasound2-dev
      - run: git config --local user.email "ci@leftshift.one" && git config --local user.name "Continuous Integration"
      - run: git checkout master && git pull --tags
      - run: cd ~/project/python && poetry install
      - run: echo 'export TARGET_MODULE=${CIRCLE_TAG#*-*-}' >> $BASH_ENV && source $BASH_ENV
      - run: echo "Target module is $TARGET_MODULE"
      - run: cd ~/project/python && poetry run install $TARGET_MODULE
      - run: cd ~/project/python && poetry run test-ci $TARGET_MODULE
      - run: cd ~/project/python && poetry run release $CIRCLE_TAG
      - run: cd ~/project/python && poetry run build $TARGET_MODULE
      - run: cd ~/project/python && poetry run publish $TARGET_MODULE
      - store_test_results:
          path: build/circleci/test-results
      - run:
          name: Cleanup release
          when: always
          command: git tag -d $CIRCLE_TAG && git push -d origin $CIRCLE_TAG
      - run:
          <<: *webhook-failed
workflows:
  version: 2
  build:
    jobs:
      - build-java:
          filters:
            tags:
              ignore: /.*/
      - build-python:
          filters:
            tags:
              ignore: /.*/
          requires:
            - build-java
      - webhook-completed:
          filters:
            tags:
              ignore: /.*/
          requires:
            - build-python
  release-module:
    jobs:
      - release-java:
          context: bintray-jcenter
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^release-(major|minor|patch).*/
      - release-python:
          context: pypi
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^release-(major|minor|patch).*/
          requires:
            - release-java
      - webhook-completed:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^release-(major|minor|patch).*/
          requires:
            - release-python
