# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gensim

import flatbuffers

class GensimFastTextSimilarityResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsGensimFastTextSimilarityResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GensimFastTextSimilarityResponse()
        x.Init(buf, n + offset)
        return x

    # GensimFastTextSimilarityResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GensimFastTextSimilarityResponse
    def Responses(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .SimilarityResponse import SimilarityResponse
            obj = SimilarityResponse()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GensimFastTextSimilarityResponse
    def ResponsesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def GensimFastTextSimilarityResponseStart(builder): builder.StartObject(1)
def GensimFastTextSimilarityResponseAddResponses(builder, responses): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(responses), 0)
def GensimFastTextSimilarityResponseStartResponsesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def GensimFastTextSimilarityResponseEnd(builder): return builder.EndObject()
