# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gensim

import flatbuffers

class GensimFastTextSimilarityResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsGensimFastTextSimilarityResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GensimFastTextSimilarityResponse()
        x.Init(buf, n + offset)
        return x

    # GensimFastTextSimilarityResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GensimFastTextSimilarityResponse
    def Probability(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def GensimFastTextSimilarityResponseStart(builder): builder.StartObject(1)
def GensimFastTextSimilarityResponseAddProbability(builder, probability): builder.PrependFloat32Slot(0, probability, 0.0)
def GensimFastTextSimilarityResponseEnd(builder): return builder.EndObject()
