# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gensim

import flatbuffers

class GensimFastTextEmbeddingResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsGensimFastTextEmbeddingResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GensimFastTextEmbeddingResponse()
        x.Init(buf, n + offset)
        return x

    # GensimFastTextEmbeddingResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GensimFastTextEmbeddingResponse
    def Vector(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .VectorElement import VectorElement
            obj = VectorElement()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GensimFastTextEmbeddingResponse
    def VectorLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def GensimFastTextEmbeddingResponseStart(builder): builder.StartObject(1)
def GensimFastTextEmbeddingResponseAddVector(builder, vector): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(vector), 0)
def GensimFastTextEmbeddingResponseStartVectorVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def GensimFastTextEmbeddingResponseEnd(builder): return builder.EndObject()
