# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gensim

class GensimMessageType(object):
    NONE = 0
    GensimFastTextEmbeddingRequest = 1
    GensimFastTextEmbeddingResponse = 2
    GensimFastTextMostSimilarRequest = 3
    GensimFastTextMostSimilarResponse = 4
    GensimFastTextSimilarityRequest = 5
    GensimFastTextSimilarityResponse = 6

