# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gensim

import flatbuffers

class VectorElement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsVectorElement(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VectorElement()
        x.Init(buf, n + offset)
        return x

    # VectorElement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VectorElement
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def VectorElementStart(builder): builder.StartObject(1)
def VectorElementAddValue(builder, value): builder.PrependFloat32Slot(0, value, 0.0)
def VectorElementEnd(builder): return builder.EndObject()
