# automatically generated by the FlatBuffers compiler, do not modify

# namespace: class2

import flatbuffers

class ClassificationClass2Request(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsClassificationClass2Request(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ClassificationClass2Request()
        x.Init(buf, n + offset)
        return x

    # ClassificationClass2Request
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ClassificationClass2Request
    def Vectors(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Vector import Vector
            obj = Vector()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ClassificationClass2Request
    def VectorsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def ClassificationClass2RequestStart(builder): builder.StartObject(1)
def ClassificationClass2RequestAddVectors(builder, vectors): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(vectors), 0)
def ClassificationClass2RequestStartVectorsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ClassificationClass2RequestEnd(builder): return builder.EndObject()
