# automatically generated by the FlatBuffers compiler, do not modify

# namespace: class2

import flatbuffers

class Vector(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsVector(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Vector()
        x.Init(buf, n + offset)
        return x

    # Vector
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Vector
    def Bytes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Vector
    def BytesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int8Flags, o)
        return 0

    # Vector
    def BytesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def VectorStart(builder): builder.StartObject(1)
def VectorAddBytes(builder, bytes): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(bytes), 0)
def VectorStartBytesVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def VectorEnd(builder): return builder.EndObject()
