/*
 * Copyright (c) 2016-2019, Leftshift One
 * __________________
 * [2019] Leftshift One
 * All Rights Reserved.
 * NOTICE:  All information contained herein is, and remains
 * the property of Leftshift One and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Leftshift One
 * and its suppliers and may be covered by Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Leftshift One.
 */

// automatically generated by the FlatBuffers compiler, do not modify

package keios.protocol.gensim.flatbuffers.fasttext;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class SimilarityRequest extends Table {
  public static SimilarityRequest getRootAsSimilarityRequest(ByteBuffer _bb) { return getRootAsSimilarityRequest(_bb, new SimilarityRequest()); }
  public static SimilarityRequest getRootAsSimilarityRequest(ByteBuffer _bb, SimilarityRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public SimilarityRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String text1() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer text1AsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer text1InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String text2() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer text2AsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer text2InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createSimilarityRequest(FlatBufferBuilder builder,
      int text1Offset,
      int text2Offset) {
    builder.startObject(2);
    SimilarityRequest.addText2(builder, text2Offset);
    SimilarityRequest.addText1(builder, text1Offset);
    return SimilarityRequest.endSimilarityRequest(builder);
  }

  public static void startSimilarityRequest(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addText1(FlatBufferBuilder builder, int text1Offset) { builder.addOffset(0, text1Offset, 0); }
  public static void addText2(FlatBufferBuilder builder, int text2Offset) { builder.addOffset(1, text2Offset, 0); }
  public static int endSimilarityRequest(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

