// automatically generated by the FlatBuffers compiler, do not modify

package keios.atlas.lucene.flatbuffers;

public final class LuceneMessageType {
  private LuceneMessageType() { }
  public static final byte NONE = 0;
  public static final byte LuceneReadRequest = 1;
  public static final byte LuceneReadResponse = 2;
  public static final byte LuceneWriteRequest = 3;
  public static final byte LuceneWriteResponse = 4;

  public static final String[] names = { "NONE", "LuceneReadRequest", "LuceneReadResponse", "LuceneWriteRequest", "LuceneWriteResponse", };

  public static String name(int e) { return names[e]; }
}

