// automatically generated by the FlatBuffers compiler, do not modify

package keios.atlas.lucene.flatbuffers;

public final class WriteResult {
  private WriteResult() { }
  public static final byte Success = 0;
  public static final byte Failure = 1;

  public static final String[] names = { "Success", "Failure", };

  public static String name(int e) { return names[e]; }
}

