// automatically generated by the FlatBuffers compiler, do not modify

package keios.protocol.spacy.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class NERSpacyResponse extends Table {
  public static NERSpacyResponse getRootAsNERSpacyResponse(ByteBuffer _bb) { return getRootAsNERSpacyResponse(_bb, new NERSpacyResponse()); }
  public static NERSpacyResponse getRootAsNERSpacyResponse(ByteBuffer _bb, NERSpacyResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public NERSpacyResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String text() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer textAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer textInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int startChar() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int endChar() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String label() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer labelAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer labelInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }

  public static int createNERSpacyResponse(FlatBufferBuilder builder,
      int textOffset,
      int startChar,
      int endChar,
      int labelOffset) {
    builder.startObject(4);
    NERSpacyResponse.addLabel(builder, labelOffset);
    NERSpacyResponse.addEndChar(builder, endChar);
    NERSpacyResponse.addStartChar(builder, startChar);
    NERSpacyResponse.addText(builder, textOffset);
    return NERSpacyResponse.endNERSpacyResponse(builder);
  }

  public static void startNERSpacyResponse(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addText(FlatBufferBuilder builder, int textOffset) { builder.addOffset(0, textOffset, 0); }
  public static void addStartChar(FlatBufferBuilder builder, int startChar) { builder.addInt(1, startChar, 0); }
  public static void addEndChar(FlatBufferBuilder builder, int endChar) { builder.addInt(2, endChar, 0); }
  public static void addLabel(FlatBufferBuilder builder, int labelOffset) { builder.addOffset(3, labelOffset, 0); }
  public static int endNERSpacyResponse(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

