# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gensim

import flatbuffers

class GensimFastTextSimilarityRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsGensimFastTextSimilarityRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GensimFastTextSimilarityRequest()
        x.Init(buf, n + offset)
        return x

    # GensimFastTextSimilarityRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GensimFastTextSimilarityRequest
    def Requests(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .SimilarityRequest import SimilarityRequest
            obj = SimilarityRequest()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GensimFastTextSimilarityRequest
    def RequestsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def GensimFastTextSimilarityRequestStart(builder): builder.StartObject(1)
def GensimFastTextSimilarityRequestAddRequests(builder, requests): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(requests), 0)
def GensimFastTextSimilarityRequestStartRequestsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def GensimFastTextSimilarityRequestEnd(builder): return builder.EndObject()
