// automatically generated by the FlatBuffers compiler, do not modify

package keios.protocol.pocketsphinx.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class PocketsphinxRequest extends Table {
  public static PocketsphinxRequest getRootAsPocketsphinxRequest(ByteBuffer _bb) { return getRootAsPocketsphinxRequest(_bb, new PocketsphinxRequest()); }
  public static PocketsphinxRequest getRootAsPocketsphinxRequest(ByteBuffer _bb, PocketsphinxRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public PocketsphinxRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int speech(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int speechLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer speechAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer speechInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createPocketsphinxRequest(FlatBufferBuilder builder,
      int speechOffset) {
    builder.startObject(1);
    PocketsphinxRequest.addSpeech(builder, speechOffset);
    return PocketsphinxRequest.endPocketsphinxRequest(builder);
  }

  public static void startPocketsphinxRequest(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addSpeech(FlatBufferBuilder builder, int speechOffset) { builder.addOffset(0, speechOffset, 0); }
  public static int createSpeechVector(FlatBufferBuilder builder, byte[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addByte(data[i]); return builder.endVector(); }
  public static void startSpeechVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endPocketsphinxRequest(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishPocketsphinxRequestBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedPocketsphinxRequestBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }
}

