// automatically generated by the FlatBuffers compiler, do not modify

package keios.protocol.pocketsphinx.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class PocketSphinxMessage extends Table {
  public static PocketSphinxMessage getRootAsPocketSphinxMessage(ByteBuffer _bb) { return getRootAsPocketSphinxMessage(_bb, new PocketSphinxMessage()); }
  public static PocketSphinxMessage getRootAsPocketSphinxMessage(ByteBuffer _bb, PocketSphinxMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public PocketSphinxMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte messageType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table message(Table obj) { int o = __offset(6); return o != 0 ? __union(obj, o) : null; }

  public static int createPocketSphinxMessage(FlatBufferBuilder builder,
      byte message_type,
      int messageOffset) {
    builder.startObject(2);
    PocketSphinxMessage.addMessage(builder, messageOffset);
    PocketSphinxMessage.addMessageType(builder, message_type);
    return PocketSphinxMessage.endPocketSphinxMessage(builder);
  }

  public static void startPocketSphinxMessage(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addMessageType(FlatBufferBuilder builder, byte messageType) { builder.addByte(0, messageType, 0); }
  public static void addMessage(FlatBufferBuilder builder, int messageOffset) { builder.addOffset(1, messageOffset, 0); }
  public static int endPocketSphinxMessage(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

