// automatically generated by the FlatBuffers compiler, do not modify

package keios.protocol.pocketsphinx.flatbuffers;

public final class PocketSphinxMessageType {
  private PocketSphinxMessageType() { }
  public static final byte NONE = 0;
  public static final byte PocketSphinxRequest = 1;
  public static final byte PocketSphinxResponse = 2;

  public static final String[] names = { "NONE", "PocketSphinxRequest", "PocketSphinxResponse", };

  public static String name(int e) { return names[e]; }
}

