# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tesseract

class TesseractMessageType(object):
    NONE = 0
    TesseractOcrRequest = 1
    TesseractOcrResponse = 2

