# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tesseract

import flatbuffers

class TesseractOcrRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTesseractOcrRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TesseractOcrRequest()
        x.Init(buf, n + offset)
        return x

    # TesseractOcrRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TesseractOcrRequest
    def Image(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # TesseractOcrRequest
    def ImageAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # TesseractOcrRequest
    def ImageLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def TesseractOcrRequestStart(builder): builder.StartObject(1)
def TesseractOcrRequestAddImage(builder, image): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(image), 0)
def TesseractOcrRequestStartImageVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def TesseractOcrRequestEnd(builder): return builder.EndObject()
