// automatically generated by the FlatBuffers compiler, do not modify

package keios.protocol.tesseract.flatbuffers;

public final class TesseractMessageType {
  private TesseractMessageType() { }
  public static final byte NONE = 0;
  public static final byte TesseractOcrRequest = 1;
  public static final byte TesseractOcrResponse = 2;

  public static final String[] names = { "NONE", "TesseractOcrRequest", "TesseractOcrResponse", };

  public static String name(int e) { return names[e]; }
}

