// automatically generated by the FlatBuffers compiler, do not modify

package keios.protocol.tesseract.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class TesseractMessage extends Table {
  public static TesseractMessage getRootAsTesseractMessage(ByteBuffer _bb) { return getRootAsTesseractMessage(_bb, new TesseractMessage()); }
  public static TesseractMessage getRootAsTesseractMessage(ByteBuffer _bb, TesseractMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public TesseractMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte messageType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table message(Table obj) { int o = __offset(6); return o != 0 ? __union(obj, o) : null; }

  public static int createTesseractMessage(FlatBufferBuilder builder,
      byte message_type,
      int messageOffset) {
    builder.startObject(2);
    TesseractMessage.addMessage(builder, messageOffset);
    TesseractMessage.addMessageType(builder, message_type);
    return TesseractMessage.endTesseractMessage(builder);
  }

  public static void startTesseractMessage(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addMessageType(FlatBufferBuilder builder, byte messageType) { builder.addByte(0, messageType, 0); }
  public static void addMessage(FlatBufferBuilder builder, int messageOffset) { builder.addOffset(1, messageOffset, 0); }
  public static int endTesseractMessage(FlatBufferBuilder builder) {
    int o = builder.endObject();
    builder.required(o, 6);  // message
    return o;
  }
  public static void finishTesseractMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedTesseractMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }
}

