// automatically generated by the FlatBuffers compiler, do not modify

package keios.protocol.spacy.flatbuffers;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class SpacyBatchRequest extends Table {
  public static SpacyBatchRequest getRootAsSpacyBatchRequest(ByteBuffer _bb) { return getRootAsSpacyBatchRequest(_bb, new SpacyBatchRequest()); }
  public static SpacyBatchRequest getRootAsSpacyBatchRequest(ByteBuffer _bb, SpacyBatchRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public SpacyBatchRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SpacyRequest requests(int j) { return requests(new SpacyRequest(), j); }
  public SpacyRequest requests(SpacyRequest obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int requestsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createSpacyBatchRequest(FlatBufferBuilder builder,
      int requestsOffset) {
    builder.startObject(1);
    SpacyBatchRequest.addRequests(builder, requestsOffset);
    return SpacyBatchRequest.endSpacyBatchRequest(builder);
  }

  public static void startSpacyBatchRequest(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addRequests(FlatBufferBuilder builder, int requestsOffset) { builder.addOffset(0, requestsOffset, 0); }
  public static int createRequestsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRequestsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endSpacyBatchRequest(FlatBufferBuilder builder) {
    int o = builder.endObject();
    builder.required(o, 4);  // requests
    return o;
  }
  public static void finishSpacyBatchRequestBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedSpacyBatchRequestBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }
}

