// automatically generated by the FlatBuffers compiler, do not modify

package keios.protocol.spacy.flatbuffers;

public final class SpacyMessageType {
  private SpacyMessageType() { }
  public static final byte NONE = 0;
  public static final byte SpacyRequest = 1;
  public static final byte SpacyBatchRequest = 2;
  public static final byte SpacyResponse = 3;
  public static final byte SpacyBatchResponse = 4;

  public static final String[] names = { "NONE", "SpacyRequest", "SpacyBatchRequest", "SpacyResponse", "SpacyBatchResponse", };

  public static String name(int e) { return names[e]; }
}

