// automatically generated by the FlatBuffers compiler, do not modify

package keios.protocol.gensim.flatbuffers.fasttext;

import java.nio.*;
import java.lang.*;

import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class GensimFastTextEmbeddingRequest extends Table {
  public static GensimFastTextEmbeddingRequest getRootAsGensimFastTextEmbeddingRequest(ByteBuffer _bb) { return getRootAsGensimFastTextEmbeddingRequest(_bb, new GensimFastTextEmbeddingRequest()); }
  public static GensimFastTextEmbeddingRequest getRootAsGensimFastTextEmbeddingRequest(ByteBuffer _bb, GensimFastTextEmbeddingRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public GensimFastTextEmbeddingRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String text() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer textAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer textInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createGensimFastTextEmbeddingRequest(FlatBufferBuilder builder,
      int textOffset) {
    builder.startObject(1);
    GensimFastTextEmbeddingRequest.addText(builder, textOffset);
    return GensimFastTextEmbeddingRequest.endGensimFastTextEmbeddingRequest(builder);
  }

  public static void startGensimFastTextEmbeddingRequest(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addText(FlatBufferBuilder builder, int textOffset) { builder.addOffset(0, textOffset, 0); }
  public static int endGensimFastTextEmbeddingRequest(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

