// automatically generated by the FlatBuffers compiler, do not modify

package keios.protocol.gensim.flatbuffers.fasttext;

import java.nio.*;
import java.lang.*;

import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class GensimFastTextSimilarityResponse extends Table {
  public static GensimFastTextSimilarityResponse getRootAsGensimFastTextSimilarityResponse(ByteBuffer _bb) { return getRootAsGensimFastTextSimilarityResponse(_bb, new GensimFastTextSimilarityResponse()); }
  public static GensimFastTextSimilarityResponse getRootAsGensimFastTextSimilarityResponse(ByteBuffer _bb, GensimFastTextSimilarityResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public GensimFastTextSimilarityResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float probability() { int o = __offset(4); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }

  public static int createGensimFastTextSimilarityResponse(FlatBufferBuilder builder,
      float probability) {
    builder.startObject(1);
    GensimFastTextSimilarityResponse.addProbability(builder, probability);
    return GensimFastTextSimilarityResponse.endGensimFastTextSimilarityResponse(builder);
  }

  public static void startGensimFastTextSimilarityResponse(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addProbability(FlatBufferBuilder builder, float probability) { builder.addFloat(0, probability, 0.0f); }
  public static int endGensimFastTextSimilarityResponse(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

