// automatically generated by the FlatBuffers compiler, do not modify

package keios.atlas.spacy.flatbuffers;

public final class Type {
  private Type() { }
  public static final byte DEP = 0;
  public static final byte NER = 1;

  public static final String[] names = { "DEP", "NER", };

  public static String name(int e) { return names[e]; }
}

