// automatically generated by the FlatBuffers compiler, do not modify

package keios.protocol.nlpaug.text.augmenter;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class FastTextAugmenter extends Table {
  public static FastTextAugmenter getRootAsFastTextAugmenter(ByteBuffer _bb) { return getRootAsFastTextAugmenter(_bb, new FastTextAugmenter()); }
  public static FastTextAugmenter getRootAsFastTextAugmenter(ByteBuffer _bb, FastTextAugmenter obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public FastTextAugmenter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean insert() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean substitute() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createFastTextAugmenter(FlatBufferBuilder builder,
      boolean insert,
      boolean substitute) {
    builder.startObject(2);
    FastTextAugmenter.addSubstitute(builder, substitute);
    FastTextAugmenter.addInsert(builder, insert);
    return FastTextAugmenter.endFastTextAugmenter(builder);
  }

  public static void startFastTextAugmenter(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addInsert(FlatBufferBuilder builder, boolean insert) { builder.addBoolean(0, insert, false); }
  public static void addSubstitute(FlatBufferBuilder builder, boolean substitute) { builder.addBoolean(1, substitute, false); }
  public static int endFastTextAugmenter(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

