// automatically generated by the FlatBuffers compiler, do not modify

package keios.protocol.nlpaug.text.augmenter;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class SyntaxTreeAugmenter extends Table {
  public static SyntaxTreeAugmenter getRootAsSyntaxTreeAugmenter(ByteBuffer _bb) { return getRootAsSyntaxTreeAugmenter(_bb, new SyntaxTreeAugmenter()); }
  public static SyntaxTreeAugmenter getRootAsSyntaxTreeAugmenter(ByteBuffer _bb, SyntaxTreeAugmenter obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public SyntaxTreeAugmenter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startSyntaxTreeAugmenter(FlatBufferBuilder builder) { builder.startObject(0); }
  public static int endSyntaxTreeAugmenter(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

