// automatically generated by the FlatBuffers compiler, do not modify

package keios.protocol.gensim.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class GensimMessage extends Table {
  public static GensimMessage getRootAsGensimMessage(ByteBuffer _bb) { return getRootAsGensimMessage(_bb, new GensimMessage()); }
  public static GensimMessage getRootAsGensimMessage(ByteBuffer _bb, GensimMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public GensimMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte messageType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table message(Table obj) { int o = __offset(6); return o != 0 ? __union(obj, o) : null; }

  public static int createGensimMessage(FlatBufferBuilder builder,
      byte message_type,
      int messageOffset) {
    builder.startObject(2);
    GensimMessage.addMessage(builder, messageOffset);
    GensimMessage.addMessageType(builder, message_type);
    return GensimMessage.endGensimMessage(builder);
  }

  public static void startGensimMessage(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addMessageType(FlatBufferBuilder builder, byte messageType) { builder.addByte(0, messageType, 0); }
  public static void addMessage(FlatBufferBuilder builder, int messageOffset) { builder.addOffset(1, messageOffset, 0); }
  public static int endGensimMessage(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

