// automatically generated by the FlatBuffers compiler, do not modify

package keios.protocol.gensim.flatbuffers;

public final class GensimMessageType {
  private GensimMessageType() { }
  public static final byte NONE = 0;
  public static final byte GensimFastTextEmbeddingRequest = 1;
  public static final byte GensimFastTextEmbeddingResponse = 2;
  public static final byte GensimFastTextMostSimilarRequest = 3;
  public static final byte GensimFastTextMostSimilarResponse = 4;
  public static final byte GensimFastTextSimilarityRequest = 5;
  public static final byte GensimFastTextSimilarityResponse = 6;

  public static final String[] names = { "NONE", "GensimFastTextEmbeddingRequest", "GensimFastTextEmbeddingResponse", "GensimFastTextMostSimilarRequest", "GensimFastTextMostSimilarResponse", "GensimFastTextSimilarityRequest", "GensimFastTextSimilarityResponse", };

  public static String name(int e) { return names[e]; }
}

