// automatically generated by the FlatBuffers compiler, do not modify

package keios.protocol.gensim.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Similarity extends Table {
  public static Similarity getRootAsSimilarity(ByteBuffer _bb) { return getRootAsSimilarity(_bb, new Similarity()); }
  public static Similarity getRootAsSimilarity(ByteBuffer _bb, Similarity obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Similarity __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String text() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer textAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer textInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public float probability() { int o = __offset(6); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }

  public static int createSimilarity(FlatBufferBuilder builder,
      int textOffset,
      float probability) {
    builder.startObject(2);
    Similarity.addProbability(builder, probability);
    Similarity.addText(builder, textOffset);
    return Similarity.endSimilarity(builder);
  }

  public static void startSimilarity(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addText(FlatBufferBuilder builder, int textOffset) { builder.addOffset(0, textOffset, 0); }
  public static void addProbability(FlatBufferBuilder builder, float probability) { builder.addFloat(1, probability, 0.0f); }
  public static int endSimilarity(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

